### ISSUE TITLE
$(( is not necessarily closed by ))

### ISSUE THREAD

**Issue by anntzer** [chrisbra/vim-zsh#2]
The syntax file currently chokes on `x=$((cmd1 | cmd2) 2>/dev/null)`, probably because it thinks `$((` is always closed by `))`.

**Comment by chrisbra** [comment]
Hi Antony!

On Di, 25 Aug 2015, Antony Lee wrote:

> The syntax file currently chokes on `x=$((cmd1 | cmd2) 2>/dev/null)`, probably because it thinks `$((` is always closed by `))`.

Thanks for the feedback. Can you check, that the last commit fixed this?

Best,
Christian
-- 
Einer Frau ihren Herzenswunsch ausreden zu wollen, gleicht dem
Versuch, den Niagara-Fall mit bloßen Händen zu stoppen.
		-- Bob Hope

**Comment by anntzer** [comment]
The commit creates another issue: now the entire string between the two parentheses (i.e. `2>/dev/null`) gets highlighted as a delimiter too.

**Comment by chrisbra** [comment]
Hi Antony!

On Mi, 26 Aug 2015, Antony Lee wrote:

> The commit creates another issue: now the entire string between the
> two parentheses (i.e. `2>/dev/null`) gets highlighted as a delimiter
> too.

Hm, that looks tricky. I would say, write this as
$( (foobar) 2>/dev/null)
which should get parsed correctly and also makes clear, this is not a 
math expression.

I am not sure, how to fix this, since the zshMathSubst highlighting 
group will get higher priority over the zshParentheses, since it starts 
earlier

Best,
Christian
-- 
Manche Menschen sind wie ein offenes Buch: lauter leere Seiten.

**Comment by anntzer** [comment]
Seems that replacing `syn region` by `syn match` with a regexp that looks something like `\V$((\_.\{-}))` should work?

**Comment by chrisbra** [comment]
Hi Antony!

On Mi, 26 Aug 2015, Antony Lee wrote:

> Seems that replacing `syn region` by `syn match` with a regexp that looks something like `\V$((\_.\{-}))` should work?

Besides being ugly, this does not work as well:

    zz=$( (cmd1 | cmd2) 2>/dev/null )
    xx=$((cmd1 | cmd2) 2>/dev/null )
    # This should always work
    yy=$((cmd1 | cmd2))

This is because xx=$(( does not start an arithmetic evaluation. I 
suggest explicitly add a space, that makes it more readable.

Best,
Christian
-- 
Alle Politiker haben Ahnung, außer Strauß, dem macht's nichts aus.

**Comment by anntzer** [comment]
Actually `yy=$((cmd1 | cmd2))` does not work, zsh seems to decide whether `$((` starts an arithmetic expression by checking whether the two parentheses get closed by consecutive parentheses:
```
$ x=$((echo 1 | cat))
zsh: bad math expression: operator expected at `1 | cat'
```
Anyways, there are workarounds, as you mentioned.

**Comment by anntzer** [comment]
A similar(?) issue: in `$(($foo-$bar))`, $foo is not highlighted.

**Comment by blueyed** [comment]
@anntzer 
Please file a new issue.
Thanks!
